USE Filiados_PTC

SELECT * FROM dbo.Filiados_PTC

--19
UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PT'
WHERE CODIGO_DO_MUNICIPIO = '36471'

--20
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PMDB'
WHERE CODIGO_DO_MUNICIPIO = '38490'


--21
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PC'
WHERE NOME_DO_MUNICIPIO = 'SANTANOPOLIS'

--22
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PV' 
SELECT  NOME_DO_PARTIDO   'Partido verde dos filiado' FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO ='SAO FELIX'

--23
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PSDB' 
SELECT  NOME_DO_PARTIDO 'Partido da Social Democracia Brasileira' FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO ='ENCRUZILHADA'

--24
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET NOME_DO_FILIADO  = 'Jorge Luis Magalhaes dos Santos'

--25
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET NOME_DO_FILIADO  = 'Renata Xavier Rodrigues'

--26
SELECT * FROM dbo.Filiados_PTC

UPDATE dbo.Filiados_PTC
SET NOME_DO_FILIADO  = 'Noel Leite da Silva'

--27
UPDATE dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO ='JOSIENE ANDRADE DE SOUZA' 

SELECT NOME_DO_FILIADO, SITUACAO_DO_REGISTRO
FROM Filiados_PTC
WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'

--28
UPDATE dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'  

SELECT NOME_DO_FILIADO, SITUACAO_DO_REGISTRO
FROM Filiados_PTC
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA' 


--29
UPDATE dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA' 

SELECT NOME_DO_FILIADO, SITUACAO_DO_REGISTRO
FROM Filiados_PTC
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA' 

--30
ALTER TABLE Filiados_PTC
     ADD SEXO_DO_FILIADO CHAR (1)
SELECT * FROM Filiados_PTC